### ISSUE TITLE
Exception (org/apache/hc/client5/http/ssl/TlsSocketStrategy) etter oppgradering av signature-api-client-java fra versjon 7.0.3 til 7.0.4

### ISSUE THREAD

**Issue by kajh** [digipost/signature-api-client-java#355]
Etter oppgradering av signature-api-client-java fra versjon 7.0.3 til 7.0.4 får vi `Factory method 'testingDirectClient' threw exception with message: org/apache/hc/client5/http/ssl/TlsSocketStrategy` ved oppstart av appen vår.

Vi har gjort som beskrevet på https://github.com/digipost/signature-api-client-java?tab=readme-ov-file#dependency

Dette er en Spring Boot 3.3.5 app.

Stacktrace ved oppstart:
```
Error creating bean with name 'testingDirectClient' defined in class path resource [no/uio/webapps/nettskjema/api/config/DirectClientConfiguration.class]: Failed to instantiate [no.digipost.signature.client.direct.DirectClient]: Factory method 'testingDirectClient' threw exception with message: org/apache/hc/client5/http/ssl/TlsSocketStrategy
   at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:795)
   at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1375)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1212)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
   at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
   at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
   at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
   at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:971)
   at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625)
   at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
   at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
   at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
   at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
   at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
   at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
   at no.uio.webapps.nettskjema.api.NettskjemaApiApplication.main(NettskjemaApiApplication.java:24)
   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
   at java.base/java.lang.reflect.Method.invoke(Unknown Source)
   at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:102)
   at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:64)
   at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:40)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tsdConfig' defined in URL [jar:nested:/app.jar/!BOOT-INF/classes/!/no/uio/webapps/nettskjema/api/config/tsd/TsdConfig.class]: Unsatisfied dependency expressed through constructor parameter 10: Error creating bean with name 'testingDirectClient' defined in class path resource [no/uio/webapps/nettskjema/api/config/DirectClientConfiguration.class]: Failed to instantiate [no.digipost.signature.client.direct.DirectClient]: Factory method 'testingDirectClient' threw exception with message: org/apache/hc/client5/http/ssl/TlsSocketStrategy
   at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:795)
   at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1375)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1212)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
   at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
   at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
   at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:409)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1355)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
   at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
   at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
   at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
   at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
   at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
   at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904)
   at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782)
   ... 24 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testingDirectClient' defined in class path resource [no/uio/webapps/nettskjema/api/config/DirectClientConfiguration.class]: Failed to instantiate [no.digipost.signature.client.direct.DirectClient]: Factory method 'testingDirectClient' threw exception with message: org/apache/hc/client5/http/ssl/TlsSocketStrategy
   at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648)
   at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:485)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1355)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
   at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
   at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
   at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
   at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
   at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
   at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904)
   at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782)
   ... 47 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [no.digipost.signature.client.direct.DirectClient]: Factory method 'testingDirectClient' threw exception with message: org/apache/hc/client5/http/ssl/TlsSocketStrategy
   at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:178)
   at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644)
   ... 61 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/apache/hc/client5/http/ssl/TlsSocketStrategy
   at no.digipost.signature.client.ClientConfiguration$Builder.<init>(ClientConfiguration.java:146)
   at no.digipost.signature.client.ClientConfiguration$Builder.<init>(ClientConfiguration.java:128)
   at no.digipost.signature.client.ClientConfiguration.builder(ClientConfiguration.java:124)
   at no.uio.webapps.nettskjema.api.config.DirectClientConfiguration.createClient(DirectClientConfiguration.java:83)
   at no.uio.webapps.nettskjema.api.config.DirectClientConfiguration.testingDirectClient(DirectClientConfiguration.java:69)
   at no.uio.webapps.nettskjema.api.config.DirectClientConfiguration$$SpringCGLIB$$0.CGLIB$testingDirectClient$0(<generated>)
   at no.uio.webapps.nettskjema.api.config.DirectClientConfiguration$$SpringCGLIB$$FastClass$$1.invoke(<generated>)
   at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
   at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:348)
   at no.uio.webapps.nettskjema.api.config.DirectClientConfiguration$$SpringCGLIB$$0.testingDirectClient(<generated>)
   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
   at java.base/java.lang.reflect.Method.invoke(Unknown Source)
   at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146)
   ... 62 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.hc.client5.http.ssl.TlsSocketStrategy
   at java.base/java.net.URLClassLoader.findClass(Unknown Source)
   at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
   at org.springframework.boot.loader.net.protocol.jar.JarUrlClassLoader.loadClass(JarUrlClassLoader.java:107)
   at org.springframework.boot.loader.launch.LaunchedClassLoader.loadClass(LaunchedClassLoader.java:91)
   at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
   ... 75 common frames omitted
"

```

**Comment by runeflobakk** [comment]
> Caused by: java.lang.ClassNotFoundException: org.apache.hc.client5.http.ssl.TlsSocketStrategy

Apache HttpClient var en av avhengighetene som ble oppgradert i v7.0.4. Dere må ha minst versjonene som deklareres her:
https://github.com/digipost/signature-api-client-java/blob/main/lib/pom.xml#L74-L83

Hvis dere har noe annet som drar inn tidligere versjon av Apache HttpClient, eller dere avhenger direkte av dette selv, så må dere oppgradere til siste versjon av disse. Gjøres typisk med `<dependencyManagement>`

**Comment by runeflobakk** [comment]
`TlsSocketStrategy` ble innført i v5.4 av Apache HttpClient
https://javadoc.io/static/org.apache.httpcomponents.client5/httpclient5/5.4/org/apache/hc/client5/http/ssl/TlsSocketStrategy.html
> Since:
> 5.4

**Comment by kajh** [comment]
Takk for svaret! `mvn dependency:tree` git følgende:
```
[INFO] +- no.digipost.signature:signature-api-client-java:jar:7.0.4:compile
[INFO] |  +- no.digipost.signature:signature-api-specification:jar:3.1.0:runtime
[INFO] |  +- no.digipost.signature:signature-api-specification-jaxb:jar:3.1.0:compile
[INFO] |  |  +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |  |  |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] |  |  +- no.digipost:jaxb-resolver-com.sun.xml.bind:jar:1.0:runtime
[INFO] |  |  |  +- com.sun.xml.bind:jaxb-impl:jar:2.3.2:runtime
[INFO] |  |  |  \- com.sun.xml.bind:jaxb-core:jar:2.3.0.1:runtime
[INFO] |  |  \- org.jvnet.jaxb:jaxb2-basics-runtime:jar:2.0.9:compile
[INFO] |  +- org.apache.httpcomponents.client5:httpclient5:jar:5.3.1:compile
[INFO] |  |  \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.2.5:compile
[INFO] |  \- org.apache.httpcomponents.core5:httpcore5:jar:5.2.5:compile
```
Er det rart at det ser ut til at Apache HttpClient 5.2.5 kommer via `no.digipost.signature:signature-api-client-java:jar:7.0.4`?

**Comment by runeflobakk** [comment]
Kan du prøve `mvn dependency:tree -Dverbose`? Da skal du få med informasjon om en versjon har blitt "managed" av noe annet, og da antar jeg at du vil se noe a la dette for httpclient5:
```
[INFO] +- no.digipost.signature:signature-api-client-java:jar:7.0.4:compile
...
[INFO] |  +- org.apache.httpcomponents.client5:httpclient5:jar:5.3.1:compile (version managed from 5.4.1)
```
Altså at versjon 5.4.1 har blitt "managed" ned til faktisk 5.3.1. Hvor denne managingen kommer fra må ligge et eller annet sted i strukturen av avhengigheter (det sier dessverre ikke `dependency:tree` noe om). Ser at f.eks. Spring Boot setter v5.3.1 i sin egen management av versjoner: https://docs.spring.io/spring-boot/appendix/dependency-versions/coordinates.html

**Comment by runeflobakk** [comment]
Topp! Versjons-konvergens kan være litt å bryne seg på noen ganger 🫤 

Generelt, man vil jo som regel når en dependency opptrer flere steder i en avhengighetsgraf at i alle fall _nyeste minor-versjon_ blir auto-resolvet som den som faktisk brukes, men å f.eks. bruke Spring Boot sin parent-POM vil sette opp en sterk prioritering på hva enn som ligger der av versjonsstyring. Det er nok derfor de også tilbyr å styre disse via properties, som i alle fall en litt kortfattet "escape"-mekanisme enn å sette opp egen dependencyManagement.

Selv foretrekker jeg å få Spring Boot sine versjoner av avhengigheter ved å bruke `spring-boot-dependencies` som en [BOM](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#bill-of-materials-bom-poms):
```xml
<dependencyManagement>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>3.3.5</version>
        <type>pom</type>
        <scope>import</scope>
    </dependency>
    ...
```
Og ikke bruke Spring Boot sin parent-POM. Rett og slett fordi med en sånn parent så har jeg mindre kontroll over hva som "blir en del av" mitt eget prosjekt sin POM, og jeg slipper å resonnere rundt om en versjon definert via en parent-POM har høyere prioritet vs. noe man deklarerer via "vanlige" dependencies i egen POM.  Men det er fordeler og ulemper med dette også. Man slipper liksom ikke unna å noen ganger måtte løse opp i versjoner som ikke blir resolvet helt optimalt.

Jeg bruker ofte "Dependency Hierarchy" i Eclipse for å debugge sånne ting. Det er ikke noe mer avansert enn et GUI-view av informasjonen man får fra `mvn dependency:tree -Dverbose`, men det er bare kneppet mer ergonomisk med litt filtrering og sånn for å navigere. Det finnes sikkert noe tilsvarende i IntelliJ, vil jeg tro.

https://youtrack.jetbrains.com/issue/IDEA-142027/Maven-Dependency-tree-view-like-eclipse
➡️ https://plugins.jetbrains.com/plugin/7179-maven-helper
