### ISSUE TITLE
unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by michaelglo** [digipost/signature-api-client-java#68]
Hei.

Jeg sitter å prøver å koble meg opp mot difi testmiljø for esignering.
Jeg får feilmeldingen "unable to find valid certification path to requested target"  både når jeg definerer .truststore(Certificates.TEST) og .truststore("/path/to/directory") i ClientConfiguration.

Jeg har fått bekreftet av DIFI at sertifikatet jeg buker i KeyStoreConfig er gyldig.

**Comment by asjafjell** [comment]
Heisann! Det kan være mye som gjør at det går galt, men det er ikke umiddelbart hva grunnen er i ditt tilfelle. Kunne du gitt oss følgende:

1.```Kodesnutt med kode dere tester med```
1.  Ett eller flere tidspunkt på når dere gjør kall hvor det feiler. Hvis de går helt gjennom til oss så kan vi se om vi ser noe på vår side. Hvis ikke får vi hjelpe dere ved å kikke på kodesnutten.

**Comment by michaelglo** [comment]
```

byte[] byteArray=null;
try {
     InputStream inputStream = new FileInputStream("C:/path/to/doc.pdf");
     String inputStreamToString = inputStream.toString();
     byteArray = inputStreamToString.getBytes();
     inputStream.close();
}
finally {
}

PortalDocument document = PortalDocument.builder("Subject", "document.pdf", byteArray).build();

Sender sender = new Sender("orgnr");
InputStream keyStore = null;
try {
	keyStore = new FileInputStream("C:/path/to/cert.jks");
	} catch (FileNotFoundException e) {
			e.printStackTrace();
        }

KeyStoreConfig keyStoreConfig = KeyStoreConfig.fromKeyStore(keyStore,
	"alias", "pas", "pass");
ClientConfiguration clientConfiguration = ClientConfiguration.builder(keyStoreConfig)
	.trustStore(Certificates.TEST)
	.globalSender(sender)
	 .build();

PortalClient client = new PortalClient(clientConfiguration);
		
PortalSigner signer = PortalSigner.identifiedByPersonalIdentificationNumber("reciverID",NotificationsUsingLookup.EMAIL_ONLY).build();
		
create job
PortalJob portalJob = PortalJob.builder(document,signer).build();

PortalJobResponse portalJobResponse = client.create(portalJob);

```

som gir følgende feilmelding:

nov 12, 2018 2:46:35 PM no.digipost.signature.client.ClientConfiguration$Builder trustStore
WARNING: Using test certificates in trust store. This should never be done for production environments.
nov 12, 2018 2:46:36 PM org.springframework.oxm.jaxb.Jaxb2Marshaller createJaxbContextFromClasses
INFO: Creating JAXBContext with classes to be bound [class no.digipost.signature.api.xml.thirdparty.xades.QualifyingProperties,class no.digipost.signature.api.xml.thirdparty.asice.XAdESSignatures,class no.digipost.signature.api.xml.XMLDirectSignatureJobRequest,class no.digipost.signature.api.xml.XMLDirectSignatureJobManifest,class no.digipost.signature.api.xml.XMLPortalSignatureJobManifest,class no.digipost.signature.api.xml.XMLPortalSignatureJobRequest]
nov 12, 2018 2:46:36 PM org.springframework.oxm.jaxb.Jaxb2Marshaller createJaxbContextFromClasses
INFO: Creating JAXBContext with classes to be bound [class no.digipost.signature.api.xml.thirdparty.xades.QualifyingProperties]
Exception in thread "main" no.digipost.signature.client.core.exceptions.SignatureException: Unable to perform SSL handshake with remote server. Some possible causes (could be others, see underlying error): 
* A certificate with the wrong KeyUsage was used. The keyUsage should be DigitalSignature
* Erroneous configuration of the trust store
* Intermediate network devices interfering with traffic (e.g. proxies)
* An attacker impersonating the server (man in the middle)
* Wrong TLS version. For Java 7, see 'JSSE tuning parameters' at https://blogs.oracle.com/java-platform-group/entry/diagnosing_tls_ssl_and_https for information about enabling the latest TLS versions
	at no.digipost.signature.client.core.internal.ClientExceptionMapper.map(ClientExceptionMapper.java:56)
	at no.digipost.signature.client.core.internal.ClientExceptionMapper.doWithMappedClientException(ClientExceptionMapper.java:39)
	at no.digipost.signature.client.core.internal.ClientHelper.call(ClientHelper.java:205)
	at no.digipost.signature.client.core.internal.ClientHelper.sendPortalSignatureJobRequest(ClientHelper.java:101)
	at no.digipost.signature.client.portal.PortalClient.create(PortalClient.java:55)
	at test.test.App.main(App.java:88)
Caused by: javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:284)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:753)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:752)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:445)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:351)
	at no.digipost.signature.client.core.internal.ClientHelper$UsingBodyParts.postAsMultiPart(ClientHelper.java:248)
	at no.digipost.signature.client.core.internal.ClientHelper.lambda$sendPortalSignatureJobRequest$1(ClientHelper.java:102)
	at no.digipost.signature.client.core.internal.ClientExceptionMapper.doWithMappedClientException(ClientExceptionMapper.java:37)
	... 4 more
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.lambda$_apply$0(HttpUrlConnector.java:382)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:195)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:189)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:223)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:300)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at java.io.BufferedWriter.flush(BufferedWriter.java:254)
	at org.glassfish.jersey.media.multipart.internal.MultiPartWriter.writeTo(MultiPartWriter.java:208)
	at org.glassfish.jersey.media.multipart.internal.MultiPartWriter.writeTo(MultiPartWriter.java:79)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1135)
	at org.glassfish.jersey.client.ClientRequest.doWriteEntity(ClientRequest.java:516)
	at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:498)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:384)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:282)
	... 16 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:105)
	at org.apache.http.ssl.SSLContextBuilder$TrustManagerDelegate.checkServerTrusted(SSLContextBuilder.java:416)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:992)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
	... 49 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 57 more

**Comment by michaelglo** [comment]
Tusen takk for raskt svar.

Dette gjorde at jeg kom meg et steg videre, men nå sitter jeg med følgende feil:

Exception in thread "main" no.digipost.signature.client.core.exceptions.UnexpectedResponseException: Expected [200 OK], but got 403 Forbidden

**Comment by asjafjell** [comment]
Du kommer i alle fall så langt gjennom at jeg finner deg i loggene. 
```Error generating cert path. Certificate C=NO, L="Akershus festning, Glacisgata 1, 0150 OSLO", O=FORSVARET - 986105174, OU=DVU, OU="BIC=Test Certificate", SERIALNUMBER=986105174, CN=FORSVARET, issuer: C=NO, O=Commfides Norge AS - 988 312 495, OU=CPN Enterprise-Norwegian SHA256 CA- TEST, OU=Commfides Trust Environment(C) 2014 Commfides Norge AS - TEST, CN=Commfides CPN Enterprise-Norwegian SHA256 CA - TEST is not issued by trusted issuer. SunCertPathBuilderException: unable to find valid certification path to requested target.
```

Usikker på hvorfor dette skjer, så skal kikke litt nå og hvis jeg ikke finner ut av det de neste ti minuttene så blir det i morgen tidlig.

**Comment by michaelglo** [comment]
høres bra ut.
Jeg prøver også å få dette implementert som webMethods løsning, men dette gir meg 

Exception in thread "main" java.lang.IllegalArgumentException: Resource class path resource [thirdparty/xmldsig-core-schema.xsd] does not exist

Har du noen anelse om dette?

**Comment by asjafjell** [comment]
Litt begynnende feilsøking viser at det sertifikatet du prøver med er utgitt fra en TEST-ca hos Commfides (CPN Enterprise-Norwegian SHA256 CA- TEST) , men vi støtter bare de som kommer fra  Commfides CPN Enterprise-Norwegian SHA256 CA - TEST2. Vi vet ikke akkurat nå hva dette betyr i praksis, men det kan du høre med Difi/Commfides om :)

**Comment by asjafjell** [comment]
Vi mistenker altså at dette sertifikatet er utgått siden du har fått sertifikatet fra en test-CA som vi ikke har lagret sertifikater til.

**Comment by asjafjell** [comment]
> høres bra ut.
> Jeg prøver også å få dette implementert som webMethods løsning, men dette gir meg
> 
> Exception in thread "main" java.lang.IllegalArgumentException: Resource class path resource [thirdparty/xmldsig-core-schema.xsd] does not exist
> 
> Har du noen anelse om dette?

Nei, dessverre. Dette er noe som høres ut som er knyttet spesifikt til deres implementasjon, og det kan jeg nok ikke bistå med.

**Comment by michaelglo** [comment]
implementasjonen i webMethods krever at vi legger ved signature-api klienten som en .jar fil. Er det en mulighet å få kompilert inn alle dependencies som en del av denne, slik at det ikke er nødvendig å lete etter riktig versjon av hver enkelt? Dette gjelder også de tre som ikke er lagret i pom filen, dvs. 

<dependency>
	<groupId>org.glassfish.jersey.inject</groupId>
	<artifactId>jersey-hk2</artifactId>
	<version>2.26</version>
</dependency>
<dependency>
	<groupId>org.slf4j</groupId>
	<artifactId>slf4j-api</artifactId>
	<version>1.7.16</version>
</dependency>
<dependency>
	<groupId>org.slf4j</groupId>
	<artifactId>slf4j-jdk14</artifactId>
	<version>1.7.16</version>
</dependency>

**Comment by michaelglo** [comment]
ang sertifikater, vil dette gi samme problem i produksjon?
Hva er kravene for produksjonssertifikater?

**Comment by StureForre** [comment]
Hei

Her er krav til sertifikater dokumentert: https://begrep.difi.no/SikkerDigitalPost/1.2.0/sikkerhet/sertifikathandtering
Som dere ser er det spesifisert her at det er ca – test2 som er støttet. Dette slo meg ikke da jeg sa at sertifikatet såg greit ut. Bortsett fra kjeden har jo sertifikatet alle de rette egenskapene.
Det vil med andre ord ikke være sertifikatrelaterte problemer så lenge rett sertifikat brukes (i henhold til dokumentasjonen)

Vennlig hilsen

Sture Domaas Førre
seniorrådgiver

M: 415 06 686
A: Skrivarvegen 2 6863 Leikanger


[logo]

Postboks 8115 Dep., 0032 Oslo

www.difi.no<file://difi/apps/Outlook%20Signatur-maler%20Difi/Maler/2017/www.difi.no>

Fra: michaelglo <notifications@github.com>
Sendt: tirsdag 13. november 2018 09.01
Til: digipost/signature-api-client-java <signature-api-client-java@noreply.github.com>
Kopi: Subscribed <subscribed@noreply.github.com>
Emne: Re: [digipost/signature-api-client-java] unable to find valid certification path to requested target (#68)


ang sertifikater, vil dette gi samme problem i produksjon?
Hva er kravene for produksjonssertifikater?

**Comment by michaelglo** [comment]
Kan du bekrefte at du fikk en forespørsel i loggen med det samme sertifikatet i dag ca 12.55?

**Comment by asjafjell** [comment]
Hvis du får feilmelding om at du ikke har tilgang, så bruker du nok fortsatt et sertifikat som er utstedt av feil CA. Om du får OK, så er alt som det skal være.
